[package]
name = "pap_course"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = { version = "0.4.19", default-features = false }
simple_logger = { version = "4.2.0", default-features = false }
